### ISSUE TITLE
Silent refresh of access token

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-webapp#10]
The MySkills WebApp authenticates users against an external OpenID Connect provider and obtains an access token via Implicit flow. Currently, there is no automatic refresh of tokens, thus users are logged off after their token has expired even if they are still working with the MySkills application.

The "angular-oauth2-oidc" module used for authentication provides support for silent refresh using a hidden iframe. See: https://manfredsteyer.github.io/angular-oauth2-oidc/docs/additional-documentation/refreshing-a-token-(silent-refresh).html

**Comment by LebedkoDmitry** [comment]
PR #23

**Comment by LebedkoDmitry** [comment]
Implemented in #23
