### ISSUE TITLE
Upgrade Angular Flex-Layout dependency version

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-webapp#14]
The dependency `@angular/flex-layout` should be updated at least to version `7.0.0-beta.22` which will fix a regression bug introduced with version `7.0.0-beta.20`.

See this issue: https://github.com/angular/flex-layout/issues/915

Meanwhile the dependency was reverted to the fixed version `7.0.0-beta.19` until the above issue has been fixed with a new release.

**Comment by LebedkoDmitry** [comment]
Implemented in #24
