### ISSUE TITLE
Support for relationships between users and projects

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-webapp#16]
Every user should be able to assign multiple projects to her/his profile. For each of those relationships the user can enter specific properties (e.g. what she/he did in that particular project). The projects related to the user should be displayed on a dedicated "my projects" view.

Display of projects related to user:

* There is a separate navigation menu item to access the personal "my projects" view for the currently authenticated user, similar to the "my skill profile" view.
* On the "my projects" page there is a list of those projects related to the currently authenticated user. The related projects are loaded via API request from the server, e.g. `GET /users/{userId}/projects` where `userId` is always the ID of the authenticated user.
* Each project list item displays the project name and the properties specific to the user-project relationship: role, tasks, start date, end date.

Assignment of projects to users:

* There is a "assign project" button on the "my projects" page allowing the currently authenticated user to assign an existing project to her/his profile.
* The "assign project" button opens the respective bottom sheet which allows the user to enter the properties for this user-project relationship:
  * Project (mandatory, only selection of existing projects)
  * Role (optional)
  * Tasks (optional)
  * Start date (mandatory)
  * End date (optional)
* Below the input fields in the "assign project" bottom sheet is a save button which allows the user to store the relationship. This triggers the API request to the server, e.g. `POST /users/{userId}/projects`.
* In the "assign project" bottom sheet there is also a cancel button which simply closes the sheet without saving.
* After saving a new project relationship the project list on the "my projects" page should be refreshed to display the new list item.

Editing/deleting project relationships:

* On each project list item on the "my projects" page there is an edit button which opens the "edit project assignment" bottom sheet for the corresponding project.
* The "edit project assignment" bottom sheet allows the user to edit the properties of the user-project relationship (role, tasks, start date, end date). The project name itself is only displayed as read-only text.
* Below the input fields in the "edit project assignment" bottom sheet is a save button which allows the user to update the relationship. This triggers the API request to the server, e.g. `PUT /users/{userId}/projects/{projectId}`.
* In the "edit project assignment" bottom sheet there is also a cancel button which simply closes the sheet without saving.
* After saving the project relationship the project list on the "my projects" page should be refreshed to display the updated values.
* On each project list item on the "my projects" page there is a delete button which allows the user to remove that user-project relationship. There is a confirmation dialog before the API request, e.g. `DELETE /users/{userId}/projects/{projectId}`, is performed.

**Comment by LebedkoDmitry** [comment]
Done in #32
