### ISSUE TITLE
Download Word document of anonymous user profiles

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-webapp#8]
Depends on #7 

The MySkills WebApp should provide an option to download anonymous user profiles as Word documents. This feature should be available when searching for users with specific skills.

Download in user search results:

* In the "Search Users By Skills" page, there is a "Download Anonymous Profile" button on each card representing an anonymous user profile matching the given search criteria.
* When clicking the download button the WebApp requests the Word document download of the anonymous user profile for the corresponding "anonymous reference ID" from the MySkills Server, for example `GET /download/users/{refId}`
* The downloaded Word document is provided to the user as a normal browser download (which may open a "save file" dialog). The document should not be viewed directly in the browser.

**Comment by LebedkoDmitry** [comment]
PR #38

**Comment by LebedkoDmitry** [comment]
Implemented in #38
